NixOS module for kupo
mlabs-haskell/kupo pull request #2
Opened 2022-08-15 03:28 UTC by euonymos

2022-09-13 11:25 UTC, brainrake requested changes
looking good, just a few minor changes needed

2022-09-13 11:25 UTC, brainrake commented on kupo-nixos-module.nix
> +      type = str;
path

2022-09-13 11:25 UTC, brainrake commented on kupo-nixos-module.nix
> +      type = str;
path

2022-09-13 11:25 UTC, brainrake commented on kupo-nixos-module.nix
> +        # [ "--workdir" "/tmp" ]
add an option or remove this (can still be added via `extraArgs`). best if systemd tmpdir support is used, see PrivateTmp

2022-09-13 11:25 UTC, brainrake commented on kupo-nixos-module.nix
> +        # Security
please run `systemd-analyze security` and try to improve based on suggestions there, unless the service breaks.

2022-09-13 11:26 UTC, brainrake commented
why do we have a fork? can we upstream?

2022-09-13 23:11 UTC, euonymos commented
> why do we have a fork? can we upstream?

I got the impression that Matthias is not really fond of Nix... 
https://github.com/CardanoSolutions/kupo/pull/55

2022-09-13 23:18 UTC, euonymos commented
> why do we have a fork? can we upstream?

BTW what's the best practice if we need a NixOS module, but upstream repo doesn't want to accept any Nix code?

2022-09-19 20:47 UTC, brainrake commented
i reckon, make a flake repo with the nixos module and reference the project repo.

2022-11-08 10:52 UTC, brainrake commented
Implemented in a separate repo.
https://github.com/mlabs-haskell/kupo-nixos

2022-11-08 10:52 UTC, closed without merging